### ISSUE TITLE
ValueError: unsupported pickle protocol: 3

### ISSUE THREAD

**Issue by goodtogood** [david-leon/Keras_CTC#1]
win8.1 64bit py2.7

> Traceback (most recent call last):
  File "mnist_ctc_v9.py", line 154, in <module>
    X_train, y_train, X_test, y_test = pickle.load(f)
  File "D:\Anaconda2\envs\mod\lib\pickle.py", line 1384, in load
    return Unpickler(file).load()
  File "D:\Anaconda2\envs\mod\lib\pickle.py", line 864, in load
    dispatch[key](self)
  File "D:\Anaconda2\envs\mod\lib\pickle.py", line 892, in load_proto
    raise ValueError, "unsupported pickle protocol: %d" % proto
ValueError: unsupported pickle protocol: 3

how to sovle this problem?
BTW would you like to make CTC compatible with latest Keras (v1.1.2)?
thx!

**Comment by david-leon** [comment]
You're supposed to run the code in Python 3.x. And yes I'll keep update with the newest Keras, recently I'm occupied with other stuffs, but the project is still on.
